# Generated by Django 4.0.3 on 2022-04-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('action_done', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='done_actions', to='notifications.action')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='contenttypes.contenttype')),
                ('next_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='notifications.action')),
                ('u_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifire', to=settings.AUTH_USER_MODEL)),
                ('u_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
